plugins {
    id 'net.darkhax.curseforgegradle' version '1.+'
    id "com.modrinth.minotaur" version "2.+"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }

    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

dependencies {
    neoForge "net.neoforged:neoforge:${neo_version}"

    // Mod Dependencies
    //modImplementation "com.cerbon:cerbons_api-neoforge-${minecraft_version}:${cerbons_api_version}"
    //modImplementation "curse.maven:golden-foods-873866:5860711"
    //modImplementation "curse.maven:monolib-968432:5838463"

    // Useful Mods
    //modCompileOnlyApi "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    //modRuntimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    //modImplementation "curse.maven:jade-324717:${jade_version_forge}"

    // All Projects Dependencies
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    implementation(include("io.github.llamalad7:mixinextras-neoforge:${mixin_extras_version}"))

    common(project(path: ":common")) { transitive false }
    shadowBundle(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }
}

processResources {
    var replaceProperties = [
            minecraft_version_range         : minecraft_version_range_forge,
            neo_version_range               : neo_version_range,
            neo_loader_version_range        : neo_loader_version_range,
            mod_id                          : mod_id,
            mod_name                        : mod_name,
            mod_license                     : mod_license,
            mod_version                     : mod_version,
            mod_authors                     : mod_authors,
            mod_description                 : mod_description,
            issues_url                      : issues_url,
            curseforge_url                  : curseforge_url,
            logo_file                       : logo_file,
            cerbons_api_version_range_forge : cerbons_api_version_range_forge
    ]
    inputs.properties replaceProperties

    filesMatching(["META-INF/neoforge.mods.toml", "pack.mcmeta"]) {
        expand replaceProperties + [project: project]
    }
}

base {
    archivesName = archives_base_name + "-NeoForge-${minecraft_version}"
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowBundle]
    archiveClassifier.set("")
}

tasks.build.dependsOn shadowJar

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

//tasks.register("publishCurseForgeAndModrinth", Task) {
//    dependsOn publishCurseForge
//    dependsOn tasks.modrinth
//}
//
//tasks.register("publishCurseForge", TaskPublishCurseForge) {
//    apiToken = System.getenv("CURSEFORGE_TOKEN")
//
//    def mainFile = upload(curseforge_project_id, jar)
//    mainFile.addModLoader("NeoForge")
//    mainFile.addGameVersion(game_versions.replaceAll(" ", "").split(","))
//
//    mainFile.releaseType = release_type
//    mainFile.changelogType = changelog_type
//    mainFile.changelog = rootProject.file(changelog).getText("UTF-8")
//
//    mainFile.addRequirement(required_dependencies_neo.replaceAll(" ", "").split(","))
//}
//
//modrinth {
//    token = System.getenv("MODRINTH_TOKEN")
//
//    projectId = modrinth_project_id
//    uploadFile = jar
//    loaders = ["neoforge"]
//
//    gameVersions = game_versions.replaceAll(" ", "").split(",") as Iterable<? extends String>
//
//    versionName = archivesName + "-" + mod_version
//    versionNumber = mod_version
//    versionType = release_type
//
//    changelog = rootProject.file(project.changelog).getText('UTF-8')
//
//    dependencies {
//        required.project required_dependencies_neo.replaceAll(" ", "").split(",")
//    }
//}